audio:
  enabled: true
  listen:
    - fire_alarm
    - scream
    - speech
    - yell
 #   - bark
detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  # 可选：默认日志级别（默认如下）
  default: warning
# 全局FFmpeg配置（推荐）
ffmpeg:
  hwaccel_args: preset-vaapi
#  hwaccel_args: []
#ffmpeg:

#  hwaccel_args: -hwaccel qsv -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format qsv
# 记录配置（推荐添加）


record:
  enabled: true

  retain:
    days: 7
    mode: motion

snapshots:
  enabled: true
  retain:
    default: 7
cameras:
  hkws:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://
          roles:
            - detect
            - record
            - audio
      # 硬件加速参数更简洁的写法
#      hwaccel_args: preset-vaapi
    detect:
      width: 704
      height: 576
      fps: 10
      # 启用检测（之前是false）
      enabled: true
    zones: {}
    review:
      alerts: {}
      detections: {}
    objects:
      # 如果需要车牌识别，添加license_plate
      track:
        - person
        - car
        # - license_plate
    motion:
      threshold: 31
      contour_area: 10
      improve_contrast: true
    audio:
      enabled: true
#  name_oshouji3:
#    enabled: true
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.123.76:8080/h264_opus.sdp
#          roles:
#            - detect
 #     hwaccel_args: preset-vaapi
 #   detect:
#      width: 1920
#      height: 1080
#      fps: 25
#      enabled: true
#    objects:
#      track:
#        - person
#        - car
        # - license_plate
#      mask: 0.357,0.19,0.34,0.685,0.703,0.723,0.688,0.208
#    zones:
#      ddd5151:
#        coordinates: 0.251,0.238,0.255,0.758,0.627,0.807,0.55,0.201
#        loitering_time: 0
#    motion:
#      threshold: 30
#      contour_area: 40
#      improve_contrast: true
#    indoor_camera:
#      genai:
#        enabled: False

    notifications:
      enabled: true
detect:
  enabled: true
semantic_search:
  enabled: true
  model: jinav2
  model_size: large
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: false
classification:
  bird:
    enabled: false